### ISSUE TITLE
wws and ws

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#87]
Hi again the wss is working well for the hub status but the hub also needs to use ws as well (think it was in the older ver) i am have had trouble getting the landing page to work. When talking to Assistant he said It's only exposing WSS and not WS as well. Looks like WS (http) is needed to display the rooms and users count and other details where WSS is used to check the hub status. Can you add the WS support back in as well. Assistant said it can run on the https but the server just does not like it and i can not get it to work. If not ill just keep fighting and try to get it to work thanks

**Comment by andruzzzhka** [comment]
To do this, you will need to either downgrade the connection (I'm not sure you can even do this) or run a second WebSocket server, which is not the best solution

**Comment by Assistant** [comment]
>Looks like WS (http) is needed to display the rooms and users count and other details where WSS is used to check the hub status.

Let me elaborate on that since it seems you understood it incorrectly.
WSS and WS are the same thing, one just uses SSL and the other one doesn't.
You need WSS if you're connecting through HTTPS, you need WS if you're connecting through HTTP.
Since my website uses HTTPS, you need WSS to check the status. Since your landing page uses HTTP you need WS for it to work. 
The best solution is to make your landing page use HTTPS and thus use WSS.
My hubs run both WS and WSS because the hub is exposing WS, and I use a reverse proxy to expose a WSS port. That is also a good solution.

**Comment by stewartgill1977** [comment]
Thanks yep i have got it running on https :)
